"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from environs import Env

# Env variables
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env("SECRET_KEY")

DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = [h for h in env.list("ALLOWED_HOSTS", delimiter=",") if h != ""]

CSRF_TRUSTED_ORIGINS = [url for url in env.list("CSRF_TRUSTED_ORIGINS", delimiter=",") if url != ""]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tracking",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

# Nebius API key
NEBIUS_API_KEY = env.str("NEBIUS_API_KEY")

# Model used for inference
# https://docs.nebius.com/studio/inference/models
# On 08.10.2026, I got the following models:
# moonshotai/Kimi-K3
# Qwen/Qwen3-235B-A22B-Instruct-2507
# google/gemma-3-27b-it
# Qwen/Qwen3-Embedding-8B
# openai/gpt-oss-120b
# Qwen/Qwen3-30B-A3B-Instruct-2507
# NousResearch/Hermes-4-405B
# nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B
# zai-org/GLM-5.1
# nvidia/Nemotron-3_5-Lightning
# openbmb/MiniCPM-V-4_5
# Qwen/Qwen3.8-27B
# deepseek-ai/DeepSeek-V4-Flash-0731
# MiniMaxAI/MiniMax-M3
# moonshotai/Kimi-K2.7-Code
# nvidia/Nemotron-3-Ultra-550b-a55b
# moonshotai/Kimi-K2.6
# nvidia/nemotron-3-super-120b-a12b
# Qwen/Qwen3.5-397B-A17B
# deepseek-ai/DeepSeek-V4-Pro
# zai-org/GLM-5.2
# zai-org/GLM-5.3-Flash
# deepseek-ai/DeepSeek-V4.1-Flash
# zai-org/GLM-5.3
# deepseek-ai/DeepSeek-V4-Pro-0813
NEBIUS_TEXT_MODEL_ID = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B"
# Vision-capable model (from the list above) used to read expense photos
NEBIUS_VISION_MODEL_ID = "openbmb/MiniCPM-V-4_5"


# telegram 
TELEGRAM_BOT_API_KEY = env.str("TELEGRAM_BOT_API_KEY")
# Random string sent by Telegram in the X-Telegram-Bot-Api-Secret-Token header
TELEGRAM_WEBHOOK_SECRET_TOKEN = env.str("TELEGRAM_WEBHOOK_SECRET_TOKEN")

# Public base URL (e.g. https://example.com)
BASE_WEB_URL = env.str("BASE_WEB_URL")

# HTTPS
HTTPS = env.bool("HTTPS")

if HTTPS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31_536_000 
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_PRELOAD = True