# Generated by Django 6.1.1 on 2026-10-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("is_bot", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("language_code", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bot user",
                "verbose_name_plural": "bot users",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=256)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent_mortgage", "Rent / Mortgage"),
                            ("property_tax", "Property Tax"),
                            ("home_maintenance", "Home Maintenance & Repairs"),
                            ("utilities", "Utilities"),
                            ("household_supplies", "Household Supplies"),
                            ("groceries", "Groceries"),
                            ("dining", "Dining & Cafés"),
                            ("food_delivery", "Food Delivery"),
                            ("public_transport", "Public Transport"),
                            ("fuel", "Fuel"),
                            ("vehicle_costs", "Vehicle Costs"),
                            ("parking_tolls", "Parking & Tolls"),
                            ("clothing", "Clothing & Shoes"),
                            ("electronics", "Electronics"),
                            ("shopping", "General Shopping"),
                            ("healthcare", "Healthcare"),
                            ("fitness", "Fitness & Sports"),
                            ("personal_care", "Personal Care"),
                            ("childcare", "Childcare & Family"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("subscriptions", "Subscriptions & Software"),
                            ("travel", "Travel"),
                            ("insurance", "Insurance"),
                            ("bank_fees", "Bank Fees & Interest"),
                            ("debt", "Debt & Loan Payments"),
                            ("savings_investments", "Savings & Investments"),
                            ("taxes", "Taxes"),
                            ("government_fees", "Government Fees & Fines"),
                            ("work_business", "Work & Business"),
                            ("pets", "Pets"),
                            ("gifts_donations", "Gifts & Donations"),
                            ("legal_professional", "Legal & Professional Services"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("telegram_update", models.JSONField()),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.telegramuser",
                    ),
                ),
            ],
        ),
    ]
