# Generated by Django 6.1.1 on 2026-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="daily_report",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="monthly_report",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="weekly_report",
            field=models.BooleanField(default=True),
        ),
    ]
