# Generated by Django 6.1.1 on 2026-10-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_telegramuser_daily_report_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramuser",
            options={},
        ),
    ]
