# Generated by Django 6.1.1 on 2026-10-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_telegramuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="default_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome"),
                    ("currency", "Default currency"),
                    ("reporting", "Report preferences"),
                    ("done", "Done"),
                ],
                default="done",
                max_length=16,
            ),
        ),
    ]
