# Generated by Django 6.1.1 on 2026-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_telegramuser_default_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="pending_delete",
            field=models.BooleanField(default=False),
        ),
    ]
