# Generated by Django 6.1.1 on 2026-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_telegramuser_pending_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="update_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
